"""Copy the Tone Palettes picks into tables_8850.ANIMA_TONE_PREFS (a generated block).

    python tools/picker/apply_tone_picks.py <dir with tones/p001.json ...>

The directory is what ArtifactData "list" with out_dir writes for collection "tones".
Each tone that differs from the defaults becomes {"w": 2 x multiplier (0 = unticked),
"efx": -2..2, "note": "..."}. Notes are kept verbatim; what Duality does with them lives
in tables_8850.ANIMA_TONE_TRAITS (hand-kept, one line per noted tone).
"""
import glob
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INFO = json.load(open(os.path.join(REPO, "tools", "picker", "tone_info.json")))


def mult(st):
    return st + 1 if st > 0 else (1 / (1 - st) if st < 0 else 1)


prefs = {}
for f in sorted(glob.glob(os.path.join(sys.argv[1], "tones", "p*.json"))):
    doc = json.load(open(f))
    pc = int(doc["pc"])
    for key, v in (doc.get("slots") or {}).items():
        c0, c32, p = (int(x) for x in key.split("-"))
        st = int(v.get("st") or 0) if "st" in v else None
        if st is None:
            w = float(v.get("w", 2))
        else:
            w = 2 * mult(st)
        if v.get("on") is False:
            w = 0
        d = {}
        if w != 2:
            d["w"] = round(w, 4)
        if int(v.get("efx") or 0):
            d["efx"] = int(v["efx"])
        if (v.get("note") or "").strip():
            d["note"] = v["note"].strip()
        if d:
            prefs.setdefault(pc, {})[(c0, c32, p)] = d

lines = ["# --- generated by tools/picker/apply_tone_picks.py from the Tone Palettes page ---",
         "ANIMA_TONE_PREFS: dict = {"]
for pc in sorted(prefs):
    cap = INFO.get(f"0-4-{pc}", ["?"])[0]
    lines.append(f"    {pc}: {{  # {pc + 1:03d} {cap}")
    for k, d in prefs[pc].items():
        name = INFO.get("%d-%d-%d" % k, ["?"])[0]
        lines.append(f"        {k}: {d!r},  # {name}")
    lines.append("    },")
lines.append("}")
lines.append("# --- end generated picks ---")
block = "\n".join(lines)
path = os.path.join(REPO, "tables_8850.py")
src = open(path).read()
pat = re.compile(r"# --- generated by tools/picker/apply_tone_picks\.py.*?# --- end generated picks ---", re.S)
if pat.search(src):
    src = pat.sub(lambda _m: block, src)
else:
    assert src.count("ANIMA_TONE_PREFS: dict = {}") == 1
    src = src.replace("ANIMA_TONE_PREFS: dict = {}", block)
open(path, "w").write(src)
print(f"{sum(len(v) for v in prefs.values())} tones on {len(prefs)} programs")
