"""CM-64 PCM half (CM-32P) tables for Voodoo (Duality 0.19.055).

Tone names: CM-64 owner's manual p.12-13 (internal PCM sounds, PC 1-64; PC 65-128 are
card sounds and are not mapped). Partials per tone live in duality.CM64_PCM_PARTIALS.

CM64_GM_PICKS: GM program (0-based) -> (use, pcm, la_level, pcm_level)
  use        "la"    the LA half plays it (Voodoo bank, as before)
             "pcm"   a PCM part plays it (pool with 2+ units; seats on one unit)
             "layer" both halves play it
  pcm        PCM program (0-based) for this GM program. On one CM-64 the seat channels
             always play PCM, so every program names its nearest tone even when use is "la".
  la_level   CC7 scale on the LA half for "layer", in percent
  pcm_level  CC7 scale on the PCM half, in percent
The seed prefers PCM wherever the manual has a fitting tone (pianos, Rhodes, organs,
guitars, basses, strings, choir, orch hit, trumpet / trombone / brass, saxes). The block
below is regenerated by tools/picker/apply_cm64_picks.py from the CM-64 picker.
"""

CM64_PCM_TONES = (
    'A.PIANO 1',
    'A.PIANO 2',
    'A.PIANO 3',
    'A.PIANO 4',
    'A.PIANO 5',
    'A.PIANO 7',
    'A.PIANO 9',
    'E.PIANO 1',
    'E.PIANO 3',
    'E.PIANO 5',
    'A.GUITAR 1',
    'A.GUITAR 3',
    'A.GUITAR 4',
    'E.GUITAR 1',
    'E.GUITAR 2',
    'SLAP 3',
    'SLAP 4',
    'SLAP 5',
    'SLAP 6',
    'SLAP 9',
    'SLAP 10',
    'SLAP 11',
    'SLAP 12',
    'FINGERED 1',
    'FINGERED 2',
    'PICKED 1',
    'PICKED 2',
    'FRETLESS 1',
    'AC.BASS',
    'CHOIR 1',
    'CHOIR 2',
    'CHOIR 3',
    'CHOIR 4',
    'STRINGS 1',
    'STRINGS 2',
    'STRINGS 3',
    'STRINGS 4',
    'E.ORGAN 2',
    'E.ORGAN 4',
    'E.ORGAN 6',
    'E.ORGAN 8',
    'E.ORGAN 9',
    'E.ORGAN 10',
    'E.ORGAN 11',
    'E.ORGAN 12',
    'E.ORGAN 13',
    'SOFT TP 1',
    'SOFT TP 3',
    'TP/TRB 1',
    'TP/TRB 2',
    'TP/TRB 3',
    'TP/TRB 4',
    'TP/TRB 5',
    'TP/TRB 6',
    'SAX 1',
    'SAX 2',
    'SAX 3',
    'SAX 5',
    'BRASS 1',
    'BRASS 2',
    'BRASS 3',
    'BRASS 4',
    'BRASS 5',
    'ORCH HIT',
)

# GM programs (0-based) the manual has a fitting PCM tone for: the seed's "pcm" picks.
# The picker marks them; the picks below are free to differ.
CM64_GM_FITTING = frozenset({
    0, 1, 2, 3, 4, 16, 17, 18, 19, 24, 25, 26, 27, 28, 32, 33, 34, 35, 36, 37, 48, 49, 52, 53, 55, 56, 57, 59, 61, 64, 65, 66, 67,
})

# --- CM64_GM_PICKS (generated) ---
CM64_GM_PICKS = {
    0: ('pcm', 0, 100, 100),  # 001 -> A.PIANO 1
    1: ('pcm', 2, 100, 100),  # 002 -> A.PIANO 3
    2: ('pcm', 6, 100, 100),  # 003 -> A.PIANO 9
    3: ('pcm', 3, 100, 100),  # 004 -> A.PIANO 4
    4: ('pcm', 7, 100, 100),  # 005 -> E.PIANO 1
    5: ('la', 9, 100, 100),  # 006 -> E.PIANO 5
    6: ('la', 10, 100, 100),  # 007 -> A.GUITAR 1
    7: ('la', 13, 100, 100),  # 008 -> E.GUITAR 1
    8: ('la', 8, 100, 100),  # 009 -> E.PIANO 3
    9: ('la', 8, 100, 100),  # 010 -> E.PIANO 3
    10: ('la', 8, 100, 100),  # 011 -> E.PIANO 3
    11: ('la', 8, 100, 100),  # 012 -> E.PIANO 3
    12: ('la', 10, 100, 100),  # 013 -> A.GUITAR 1
    13: ('la', 10, 100, 100),  # 014 -> A.GUITAR 1
    14: ('la', 9, 100, 100),  # 015 -> E.PIANO 5
    15: ('la', 11, 100, 100),  # 016 -> A.GUITAR 3
    16: ('pcm', 37, 100, 100),  # 017 -> E.ORGAN 2
    17: ('pcm', 38, 100, 100),  # 018 -> E.ORGAN 4
    18: ('pcm', 41, 100, 100),  # 019 -> E.ORGAN 9
    19: ('pcm', 45, 100, 100),  # 020 -> E.ORGAN 13
    20: ('la', 43, 100, 100),  # 021 -> E.ORGAN 11
    21: ('la', 44, 100, 100),  # 022 -> E.ORGAN 12
    22: ('la', 55, 100, 100),  # 023 -> SAX 2
    23: ('la', 44, 100, 100),  # 024 -> E.ORGAN 12
    24: ('pcm', 10, 100, 100),  # 025 -> A.GUITAR 1
    25: ('pcm', 11, 100, 100),  # 026 -> A.GUITAR 3
    26: ('pcm', 13, 100, 100),  # 027 -> E.GUITAR 1
    27: ('pcm', 13, 100, 100),  # 028 -> E.GUITAR 1
    28: ('pcm', 14, 100, 100),  # 029 -> E.GUITAR 2
    29: ('la', 13, 100, 100),  # 030 -> E.GUITAR 1
    30: ('la', 13, 100, 100),  # 031 -> E.GUITAR 1
    31: ('la', 10, 100, 100),  # 032 -> A.GUITAR 1
    32: ('pcm', 28, 100, 100),  # 033 -> AC.BASS
    33: ('pcm', 23, 100, 100),  # 034 -> FINGERED 1
    34: ('pcm', 25, 100, 100),  # 035 -> PICKED 1
    35: ('pcm', 27, 100, 100),  # 036 -> FRETLESS 1
    36: ('pcm', 15, 100, 100),  # 037 -> SLAP 3
    37: ('pcm', 17, 100, 100),  # 038 -> SLAP 5
    38: ('la', 25, 100, 100),  # 039 -> PICKED 1
    39: ('la', 23, 100, 100),  # 040 -> FINGERED 1
    40: ('la', 34, 100, 100),  # 041 -> STRINGS 2
    41: ('la', 34, 100, 100),  # 042 -> STRINGS 2
    42: ('la', 34, 100, 100),  # 043 -> STRINGS 2
    43: ('la', 28, 100, 100),  # 044 -> AC.BASS
    44: ('la', 33, 100, 100),  # 045 -> STRINGS 1
    45: ('la', 10, 100, 100),  # 046 -> A.GUITAR 1
    46: ('la', 10, 100, 100),  # 047 -> A.GUITAR 1
    47: ('la', 63, 100, 100),  # 048 -> ORCH HIT
    48: ('pcm', 33, 100, 100),  # 049 -> STRINGS 1
    49: ('pcm', 35, 100, 100),  # 050 -> STRINGS 3
    50: ('la', 34, 100, 100),  # 051 -> STRINGS 2
    51: ('la', 36, 100, 100),  # 052 -> STRINGS 4
    52: ('pcm', 29, 100, 100),  # 053 -> CHOIR 1
    53: ('pcm', 30, 100, 100),  # 054 -> CHOIR 2
    54: ('la', 29, 100, 100),  # 055 -> CHOIR 1
    55: ('pcm', 63, 100, 100),  # 056 -> ORCH HIT
    56: ('pcm', 48, 100, 100),  # 057 -> TP/TRB 1
    57: ('pcm', 49, 100, 100),  # 058 -> TP/TRB 2
    58: ('la', 53, 100, 100),  # 059 -> TP/TRB 6
    59: ('pcm', 46, 100, 100),  # 060 -> SOFT TP 1
    60: ('la', 49, 100, 100),  # 061 -> TP/TRB 2
    61: ('pcm', 58, 100, 100),  # 062 -> BRASS 1
    62: ('la', 60, 100, 100),  # 063 -> BRASS 3
    63: ('la', 61, 100, 100),  # 064 -> BRASS 4
    64: ('pcm', 56, 100, 100),  # 065 -> SAX 3
    65: ('pcm', 54, 100, 100),  # 066 -> SAX 1
    66: ('pcm', 55, 100, 100),  # 067 -> SAX 2
    67: ('pcm', 57, 100, 100),  # 068 -> SAX 5
    68: ('la', 56, 100, 100),  # 069 -> SAX 3
    69: ('la', 55, 100, 100),  # 070 -> SAX 2
    70: ('la', 57, 100, 100),  # 071 -> SAX 5
    71: ('la', 55, 100, 100),  # 072 -> SAX 2
    72: ('la', 30, 100, 100),  # 073 -> CHOIR 2
    73: ('la', 30, 100, 100),  # 074 -> CHOIR 2
    74: ('la', 30, 100, 100),  # 075 -> CHOIR 2
    75: ('la', 30, 100, 100),  # 076 -> CHOIR 2
    76: ('la', 30, 100, 100),  # 077 -> CHOIR 2
    77: ('la', 30, 100, 100),  # 078 -> CHOIR 2
    78: ('la', 30, 100, 100),  # 079 -> CHOIR 2
    79: ('la', 30, 100, 100),  # 080 -> CHOIR 2
    80: ('la', 54, 100, 100),  # 081 -> SAX 1
    81: ('la', 58, 100, 100),  # 082 -> BRASS 1
    82: ('la', 37, 100, 100),  # 083 -> E.ORGAN 2
    83: ('la', 30, 100, 100),  # 084 -> CHOIR 2
    84: ('la', 13, 100, 100),  # 085 -> E.GUITAR 1
    85: ('la', 29, 100, 100),  # 086 -> CHOIR 1
    86: ('la', 60, 100, 100),  # 087 -> BRASS 3
    87: ('la', 25, 100, 100),  # 088 -> PICKED 1
    88: ('la', 33, 100, 100),  # 089 -> STRINGS 1
    89: ('la', 33, 100, 100),  # 090 -> STRINGS 1
    90: ('la', 60, 100, 100),  # 091 -> BRASS 3
    91: ('la', 29, 100, 100),  # 092 -> CHOIR 1
    92: ('la', 33, 100, 100),  # 093 -> STRINGS 1
    93: ('la', 8, 100, 100),  # 094 -> E.PIANO 3
    94: ('la', 29, 100, 100),  # 095 -> CHOIR 1
    95: ('la', 33, 100, 100),  # 096 -> STRINGS 1
    96: ('la', 8, 100, 100),  # 097 -> E.PIANO 3
    97: ('la', 33, 100, 100),  # 098 -> STRINGS 1
    98: ('la', 8, 100, 100),  # 099 -> E.PIANO 3
    99: ('la', 10, 100, 100),  # 100 -> A.GUITAR 1
    100: ('la', 8, 100, 100),  # 101 -> E.PIANO 3
    101: ('la', 29, 100, 100),  # 102 -> CHOIR 1
    102: ('la', 8, 100, 100),  # 103 -> E.PIANO 3
    103: ('la', 33, 100, 100),  # 104 -> STRINGS 1
    104: ('la', 11, 100, 100),  # 105 -> A.GUITAR 3
    105: ('la', 11, 100, 100),  # 106 -> A.GUITAR 3
    106: ('la', 10, 100, 100),  # 107 -> A.GUITAR 1
    107: ('la', 10, 100, 100),  # 108 -> A.GUITAR 1
    108: ('la', 8, 100, 100),  # 109 -> E.PIANO 3
    109: ('la', 56, 100, 100),  # 110 -> SAX 3
    110: ('la', 34, 100, 100),  # 111 -> STRINGS 2
    111: ('la', 56, 100, 100),  # 112 -> SAX 3
    112: ('la', 8, 100, 100),  # 113 -> E.PIANO 3
    113: ('la', 8, 100, 100),  # 114 -> E.PIANO 3
    114: ('la', 8, 100, 100),  # 115 -> E.PIANO 3
    115: ('la', 10, 100, 100),  # 116 -> A.GUITAR 1
    116: ('la', 63, 100, 100),  # 117 -> ORCH HIT
    117: ('la', 63, 100, 100),  # 118 -> ORCH HIT
    118: ('la', 63, 100, 100),  # 119 -> ORCH HIT
    119: ('la', 33, 100, 100),  # 120 -> STRINGS 1
    120: ('la', 14, 100, 100),  # 121 -> E.GUITAR 2
    121: ('la', 30, 100, 100),  # 122 -> CHOIR 2
    122: ('la', 33, 100, 100),  # 123 -> STRINGS 1
    123: ('la', 30, 100, 100),  # 124 -> CHOIR 2
    124: ('la', 8, 100, 100),  # 125 -> E.PIANO 3
    125: ('la', 63, 100, 100),  # 126 -> ORCH HIT
    126: ('la', 33, 100, 100),  # 127 -> STRINGS 1
    127: ('la', 63, 100, 100),  # 128 -> ORCH HIT
}
CM64_GM_NOTES: dict = {
}
# --- end CM64_GM_PICKS ---

CM64_USES = ("la", "pcm", "layer")


def cm64_gm_pick(program: int):
    """(use, pcm program, la level %, pcm level %) for a GM program (0-based)."""
    return CM64_GM_PICKS.get(int(program) & 0x7F, ("la", 0, 100, 100))
