"""CM-64 PCM half (CM-32P) tables for Voodoo (Duality 0.19.055).

Tone names: CM-64 owner's manual p.12-13 (internal PCM sounds, PC 1-64; PC 65-128 are
card sounds and are not mapped). Partials per tone live in duality.CM64_PCM_PARTIALS.

CM64_GM_PICKS: GM program (0-based) -> (use, pcm, la_level, pcm_level)
  use        "la"    the LA half plays it (Voodoo bank, as before)
             "pcm"   a PCM part plays it (pool with 2+ units; seats on one unit)
             "layer" both halves play it
  pcm        PCM program (0-based) for this GM program. On one CM-64 the seat channels
             always play PCM, so every program names its nearest tone even when use is "la".
  la_level   CC7 scale on the LA half for "layer", in percent
  pcm_level  CC7 scale on the PCM half, in percent
The seed prefers PCM wherever the manual has a fitting tone (pianos, Rhodes, organs,
guitars, basses, strings, choir, orch hit, trumpet / trombone / brass, saxes). The block
below is regenerated by tools/picker/apply_cm64_picks.py from the CM-64 picker.
"""

CM64_PCM_TONES = (
    'A.PIANO 1',
    'A.PIANO 2',
    'A.PIANO 3',
    'A.PIANO 4',
    'A.PIANO 5',
    'A.PIANO 7',
    'A.PIANO 9',
    'E.PIANO 1',
    'E.PIANO 3',
    'E.PIANO 5',
    'A.GUITAR 1',
    'A.GUITAR 3',
    'A.GUITAR 4',
    'E.GUITAR 1',
    'E.GUITAR 2',
    'SLAP 3',
    'SLAP 4',
    'SLAP 5',
    'SLAP 6',
    'SLAP 9',
    'SLAP 10',
    'SLAP 11',
    'SLAP 12',
    'FINGERED 1',
    'FINGERED 2',
    'PICKED 1',
    'PICKED 2',
    'FRETLESS 1',
    'AC.BASS',
    'CHOIR 1',
    'CHOIR 2',
    'CHOIR 3',
    'CHOIR 4',
    'STRINGS 1',
    'STRINGS 2',
    'STRINGS 3',
    'STRINGS 4',
    'E.ORGAN 2',
    'E.ORGAN 4',
    'E.ORGAN 6',
    'E.ORGAN 8',
    'E.ORGAN 9',
    'E.ORGAN 10',
    'E.ORGAN 11',
    'E.ORGAN 12',
    'E.ORGAN 13',
    'SOFT TP 1',
    'SOFT TP 3',
    'TP/TRB 1',
    'TP/TRB 2',
    'TP/TRB 3',
    'TP/TRB 4',
    'TP/TRB 5',
    'TP/TRB 6',
    'SAX 1',
    'SAX 2',
    'SAX 3',
    'SAX 5',
    'BRASS 1',
    'BRASS 2',
    'BRASS 3',
    'BRASS 4',
    'BRASS 5',
    'ORCH HIT',
)

# PCM tone (PC 1-64) -> the nearest GM program: Anima's categories and GM-numbered sets on the PCM
# channels (11-16) of a native CM-64 stream.
CM64_PCM_GM = (
      0,  #  1 A.PIANO 1
      0,  #  2 A.PIANO 2
      1,  #  3 A.PIANO 3
      3,  #  4 A.PIANO 4
      0,  #  5 A.PIANO 5
      0,  #  6 A.PIANO 7
      1,  #  7 A.PIANO 9
      4,  #  8 E.PIANO 1
      4,  #  9 E.PIANO 3
      4,  # 10 E.PIANO 5
     24,  # 11 A.GUITAR 1
     25,  # 12 A.GUITAR 3
     25,  # 13 A.GUITAR 4
     27,  # 14 E.GUITAR 1
     28,  # 15 E.GUITAR 2
     36,  # 16 SLAP 3
     36,  # 17 SLAP 4
     37,  # 18 SLAP 5
     37,  # 19 SLAP 6
     36,  # 20 SLAP 9
     36,  # 21 SLAP 10
     37,  # 22 SLAP 11
     37,  # 23 SLAP 12
     33,  # 24 FINGERED 1
     33,  # 25 FINGERED 2
     34,  # 26 PICKED 1
     34,  # 27 PICKED 2
     35,  # 28 FRETLESS 1
     32,  # 29 AC.BASS
     52,  # 30 CHOIR 1
     53,  # 31 CHOIR 2
     52,  # 32 CHOIR 3
     53,  # 33 CHOIR 4
     48,  # 34 STRINGS 1
     48,  # 35 STRINGS 2
     49,  # 36 STRINGS 3
     48,  # 37 STRINGS 4
     16,  # 38 E.ORGAN 2
     17,  # 39 E.ORGAN 4
     16,  # 40 E.ORGAN 6
     16,  # 41 E.ORGAN 8
     18,  # 42 E.ORGAN 9
     16,  # 43 E.ORGAN 10
     17,  # 44 E.ORGAN 11
     18,  # 45 E.ORGAN 12
     16,  # 46 E.ORGAN 13
     59,  # 47 SOFT TP 1
     59,  # 48 SOFT TP 3
     56,  # 49 TP/TRB 1
     57,  # 50 TP/TRB 2
     56,  # 51 TP/TRB 3
     56,  # 52 TP/TRB 4
     61,  # 53 TP/TRB 5
     61,  # 54 TP/TRB 6
     65,  # 55 SAX 1
     66,  # 56 SAX 2
     64,  # 57 SAX 3
     67,  # 58 SAX 5
     61,  # 59 BRASS 1
     61,  # 60 BRASS 2
     61,  # 61 BRASS 3
     61,  # 62 BRASS 4
     61,  # 63 BRASS 5
     55,  # 64 ORCH HIT
)

# CM-32L sound effects in the rhythm part (CM-64 manual p.11; factory map read from a fresh
# gearmulator CM-64 with tools/cm_rhythm_dump.py, 2026-10-04): key -> (timbre, level, pan, reverb).
# Keys 76-108 hold rhythm timbres 94-126 in order, all centre pan with reverb.
CM32L_SFX_FACTORY = {k: (94 + k - 76, 100, 7, 1) for k in range(76, 109)}
CM32L_SFX_NAMES = (
    "Laughing", "Screaming", "Punch", "Heartbeat", "Footsteps 1", "Footsteps 2", "Applause", "Creaking",
    "Door", "Scratch", "Windchime", "Engine", "Car-stop", "Car-pass", "Crash", "Siren", "Train", "Jet",
    "Helicopter", "Starship", "Pistol", "Machinegun", "Lasergun", "Explosion", "Dog", "Horse", "Birds",
    "Rain", "Thunder", "Wind", "Waves", "Stream", "Bubble",
)   # keys 76-108
# Under Voodoo a CM out keeps GM percussion on 35-81, so the six effects GM covers (76-81) move
# to keys 24-29 (unused by GM1); 82-108 keep their factory places.
CM_VOODOO_SFX = {**{24 + i: CM32L_SFX_FACTORY[76 + i] for i in range(6)},
                 **{k: CM32L_SFX_FACTORY[k] for k in range(82, 109)}}

# GM programs (0-based) the manual has a fitting PCM tone for: the seed's "pcm" picks.
# The picker marks them; the picks below are free to differ.
CM64_GM_FITTING = frozenset({
    0, 1, 2, 3, 4, 16, 17, 18, 19, 24, 25, 26, 27, 28, 32, 33, 34, 35, 36, 37, 48, 49, 52, 53, 55, 56, 57, 59, 61, 64, 65, 66, 67,
})

# --- CM64_GM_PICKS (generated) ---
CM64_GM_PICKS = {
    0: ('pcm', 0, 100, 100),  # 001 -> A.PIANO 1
    1: ('pcm', 2, 100, 100),  # 002 -> A.PIANO 3
    2: ('pcm', 6, 100, 100),  # 003 -> A.PIANO 9
    3: ('pcm', 3, 100, 100),  # 004 -> A.PIANO 4
    4: ('pcm', 7, 100, 100),  # 005 -> E.PIANO 1
    5: ('la', 9, 100, 100),  # 006 -> E.PIANO 5
    6: ('la', 10, 100, 100),  # 007 -> A.GUITAR 1
    7: ('la', 13, 100, 100),  # 008 -> E.GUITAR 1
    8: ('la', 8, 100, 100),  # 009 -> E.PIANO 3
    9: ('la', 8, 100, 100),  # 010 -> E.PIANO 3
    10: ('la', 8, 100, 100),  # 011 -> E.PIANO 3
    11: ('la', 8, 100, 100),  # 012 -> E.PIANO 3
    12: ('la', 10, 100, 100),  # 013 -> A.GUITAR 1
    13: ('la', 10, 100, 100),  # 014 -> A.GUITAR 1
    14: ('la', 9, 100, 100),  # 015 -> E.PIANO 5
    15: ('la', 11, 100, 100),  # 016 -> A.GUITAR 3
    16: ('pcm', 37, 100, 100),  # 017 -> E.ORGAN 2
    17: ('pcm', 38, 100, 100),  # 018 -> E.ORGAN 4
    18: ('pcm', 41, 100, 100),  # 019 -> E.ORGAN 9
    19: ('pcm', 45, 100, 100),  # 020 -> E.ORGAN 13
    20: ('la', 43, 100, 100),  # 021 -> E.ORGAN 11
    21: ('la', 44, 100, 100),  # 022 -> E.ORGAN 12
    22: ('la', 55, 100, 100),  # 023 -> SAX 2
    23: ('la', 44, 100, 100),  # 024 -> E.ORGAN 12
    24: ('pcm', 10, 100, 100),  # 025 -> A.GUITAR 1
    25: ('pcm', 11, 100, 100),  # 026 -> A.GUITAR 3
    26: ('pcm', 13, 100, 100),  # 027 -> E.GUITAR 1
    27: ('pcm', 13, 100, 100),  # 028 -> E.GUITAR 1
    28: ('pcm', 14, 100, 100),  # 029 -> E.GUITAR 2
    29: ('la', 13, 100, 100),  # 030 -> E.GUITAR 1
    30: ('la', 13, 100, 100),  # 031 -> E.GUITAR 1
    31: ('la', 10, 100, 100),  # 032 -> A.GUITAR 1
    32: ('pcm', 28, 100, 100),  # 033 -> AC.BASS
    33: ('pcm', 23, 100, 100),  # 034 -> FINGERED 1
    34: ('pcm', 25, 100, 100),  # 035 -> PICKED 1
    35: ('pcm', 27, 100, 100),  # 036 -> FRETLESS 1
    36: ('pcm', 15, 100, 100),  # 037 -> SLAP 3
    37: ('pcm', 17, 100, 100),  # 038 -> SLAP 5
    38: ('la', 25, 100, 100),  # 039 -> PICKED 1
    39: ('la', 23, 100, 100),  # 040 -> FINGERED 1
    40: ('la', 34, 100, 100),  # 041 -> STRINGS 2
    41: ('la', 34, 100, 100),  # 042 -> STRINGS 2
    42: ('la', 34, 100, 100),  # 043 -> STRINGS 2
    43: ('la', 28, 100, 100),  # 044 -> AC.BASS
    44: ('la', 33, 100, 100),  # 045 -> STRINGS 1
    45: ('la', 10, 100, 100),  # 046 -> A.GUITAR 1
    46: ('la', 10, 100, 100),  # 047 -> A.GUITAR 1
    47: ('la', 63, 100, 100),  # 048 -> ORCH HIT
    48: ('pcm', 33, 100, 100),  # 049 -> STRINGS 1
    49: ('pcm', 35, 100, 100),  # 050 -> STRINGS 3
    50: ('la', 34, 100, 100),  # 051 -> STRINGS 2
    51: ('la', 36, 100, 100),  # 052 -> STRINGS 4
    52: ('pcm', 29, 100, 100),  # 053 -> CHOIR 1
    53: ('pcm', 30, 100, 100),  # 054 -> CHOIR 2
    54: ('la', 29, 100, 100),  # 055 -> CHOIR 1
    55: ('pcm', 63, 100, 100),  # 056 -> ORCH HIT
    56: ('pcm', 48, 100, 100),  # 057 -> TP/TRB 1
    57: ('pcm', 49, 100, 100),  # 058 -> TP/TRB 2
    58: ('la', 53, 100, 100),  # 059 -> TP/TRB 6
    59: ('pcm', 46, 100, 100),  # 060 -> SOFT TP 1
    60: ('la', 49, 100, 100),  # 061 -> TP/TRB 2
    61: ('pcm', 58, 100, 100),  # 062 -> BRASS 1
    62: ('la', 60, 100, 100),  # 063 -> BRASS 3
    63: ('la', 61, 100, 100),  # 064 -> BRASS 4
    64: ('pcm', 56, 100, 100),  # 065 -> SAX 3
    65: ('pcm', 54, 100, 100),  # 066 -> SAX 1
    66: ('pcm', 55, 100, 100),  # 067 -> SAX 2
    67: ('pcm', 57, 100, 100),  # 068 -> SAX 5
    68: ('la', 56, 100, 100),  # 069 -> SAX 3
    69: ('la', 55, 100, 100),  # 070 -> SAX 2
    70: ('la', 57, 100, 100),  # 071 -> SAX 5
    71: ('la', 55, 100, 100),  # 072 -> SAX 2
    72: ('la', 30, 100, 100),  # 073 -> CHOIR 2
    73: ('la', 30, 100, 100),  # 074 -> CHOIR 2
    74: ('la', 30, 100, 100),  # 075 -> CHOIR 2
    75: ('la', 30, 100, 100),  # 076 -> CHOIR 2
    76: ('la', 30, 100, 100),  # 077 -> CHOIR 2
    77: ('la', 30, 100, 100),  # 078 -> CHOIR 2
    78: ('la', 30, 100, 100),  # 079 -> CHOIR 2
    79: ('la', 30, 100, 100),  # 080 -> CHOIR 2
    80: ('la', 54, 100, 100),  # 081 -> SAX 1
    81: ('la', 58, 100, 100),  # 082 -> BRASS 1
    82: ('la', 37, 100, 100),  # 083 -> E.ORGAN 2
    83: ('la', 30, 100, 100),  # 084 -> CHOIR 2
    84: ('la', 13, 100, 100),  # 085 -> E.GUITAR 1
    85: ('la', 29, 100, 100),  # 086 -> CHOIR 1
    86: ('la', 60, 100, 100),  # 087 -> BRASS 3
    87: ('la', 25, 100, 100),  # 088 -> PICKED 1
    88: ('la', 33, 100, 100),  # 089 -> STRINGS 1
    89: ('la', 33, 100, 100),  # 090 -> STRINGS 1
    90: ('la', 60, 100, 100),  # 091 -> BRASS 3
    91: ('la', 29, 100, 100),  # 092 -> CHOIR 1
    92: ('la', 33, 100, 100),  # 093 -> STRINGS 1
    93: ('la', 8, 100, 100),  # 094 -> E.PIANO 3
    94: ('la', 29, 100, 100),  # 095 -> CHOIR 1
    95: ('la', 33, 100, 100),  # 096 -> STRINGS 1
    96: ('la', 8, 100, 100),  # 097 -> E.PIANO 3
    97: ('la', 33, 100, 100),  # 098 -> STRINGS 1
    98: ('la', 8, 100, 100),  # 099 -> E.PIANO 3
    99: ('la', 10, 100, 100),  # 100 -> A.GUITAR 1
    100: ('la', 8, 100, 100),  # 101 -> E.PIANO 3
    101: ('la', 29, 100, 100),  # 102 -> CHOIR 1
    102: ('la', 8, 100, 100),  # 103 -> E.PIANO 3
    103: ('la', 33, 100, 100),  # 104 -> STRINGS 1
    104: ('la', 11, 100, 100),  # 105 -> A.GUITAR 3
    105: ('la', 11, 100, 100),  # 106 -> A.GUITAR 3
    106: ('la', 10, 100, 100),  # 107 -> A.GUITAR 1
    107: ('la', 10, 100, 100),  # 108 -> A.GUITAR 1
    108: ('la', 8, 100, 100),  # 109 -> E.PIANO 3
    109: ('la', 56, 100, 100),  # 110 -> SAX 3
    110: ('la', 34, 100, 100),  # 111 -> STRINGS 2
    111: ('la', 56, 100, 100),  # 112 -> SAX 3
    112: ('la', 8, 100, 100),  # 113 -> E.PIANO 3
    113: ('la', 8, 100, 100),  # 114 -> E.PIANO 3
    114: ('la', 8, 100, 100),  # 115 -> E.PIANO 3
    115: ('la', 10, 100, 100),  # 116 -> A.GUITAR 1
    116: ('la', 63, 100, 100),  # 117 -> ORCH HIT
    117: ('la', 63, 100, 100),  # 118 -> ORCH HIT
    118: ('la', 63, 100, 100),  # 119 -> ORCH HIT
    119: ('la', 33, 100, 100),  # 120 -> STRINGS 1
    120: ('la', 14, 100, 100),  # 121 -> E.GUITAR 2
    121: ('la', 30, 100, 100),  # 122 -> CHOIR 2
    122: ('la', 33, 100, 100),  # 123 -> STRINGS 1
    123: ('la', 30, 100, 100),  # 124 -> CHOIR 2
    124: ('la', 8, 100, 100),  # 125 -> E.PIANO 3
    125: ('la', 63, 100, 100),  # 126 -> ORCH HIT
    126: ('la', 33, 100, 100),  # 127 -> STRINGS 1
    127: ('la', 63, 100, 100),  # 128 -> ORCH HIT
}
CM64_GM_NOTES: dict = {
}
# --- end CM64_GM_PICKS ---

CM64_USES = ("la", "pcm", "layer")


def cm64_gm_pick(program: int):
    """(use, pcm program, la level %, pcm level %) for a GM program (0-based)."""
    return CM64_GM_PICKS.get(int(program) & 0x7F, ("la", 0, 100, 100))
