"""Regenerate the older-map and CM-64 tone lists in tables_8850.py from the SC-8850 ROM data.

    python tools/gen_unique_tones.py <sc-8850.json>

sc-8850.json is shingo45endo/tone-browser's dump (tones, voices, waves per bank/map/program).

Rules (per GM program 0-119; the 8850 map's tones in _C00 are always offered):
  * SC-55 / SC-88 / 88Pro maps (CC32 1/2/3) and CM-64 (CC00 126/127 on the SC-55 map): a tone is
    offered unless its tone data (voices, waveforms, parameters; not the name) is identical to an
    8850-map tone or to a tone already offered on that program (newest map wins: 88Pro, 88, 55).
    Waveforms alone are not enough: the 88Pro Piano 1 uses the Steinway-D samples the 8850 map
    has only inside its Honky-tonk, and is a different piano from the 8850's.
"""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
import tables_8850 as T  # noqa: E402

d = json.load(open(sys.argv[1]))
tm = {(t["bankM"], t["bankL"], t["prog"]): t for t in d["toneMaps"]}


def res(ref):
    _, a, i = ref.split("/")
    return d[a][int(i)]


def tones(t):
    if "combiRef" in t:
        return [res(s["toneRef"]["$ref"]) for s in res(t["combiRef"]["$ref"])["toneSlots"]]
    return [res(t["toneRef"]["$ref"])]


def waves(t):
    return frozenset(v["waveNo"] for x in tones(t) for v in x["voices"] if "waveNo" in v)


def sig(t):  # the sound itself: common params (not the name) + every voice
    return tuple((tuple(x["commonBytes"][12:]), tuple((tuple(v["bytes"]), v.get("waveNo")) for v in x["voices"]))
                 for x in tones(t))


def name(k):
    t = tm[k]
    return (t.get("toneRef") or t.get("combiRef"))["name"].rstrip(": ").strip()


w8850, s8850 = set(), set()
for (m0, m, pc), t in tm.items():
    if m == 4 and m0 not in (126, 127):
        w8850 |= waves(t)
        s8850.add(sig(t))

old, cm_drop = {}, []
cm_seen = set()
for pc in range(120):
    have = []
    for m in (3, 2, 1):
        for c0 in range(126):
            k = (c0, m, pc)
            if k in tm:
                s = sig(tm[k])
                if s not in s8850 and s not in have:
                    have.append(s)
                    old.setdefault(pc, []).append(k)
    for k in T._CM.get(pc, []):
        if k not in tm:
            continue
        s = sig(tm[k])
        if s in s8850 or s in cm_seen:
            cm_drop.append(k)
        else:
            cm_seen.add(s)

lines = ["# --- generated by tools/gen_unique_tones.py: do not edit by hand ---",
         "# Older-map tones (CC32 3 = 88Pro, 2 = SC-88, 1 = SC-55) whose tone data no 8850-map tone shares.",
         "_OLD_MAP_UNIQUE = {"]
for pc in sorted(old):
    body = ", ".join(f"({c0}, {m}, {p})" for c0, m, p in old[pc])
    names = " / ".join(f"{name(k)} [{ {3: '88Pro', 2: '88', 1: '55'}[k[1]] }]" for k in old[pc])
    lines.append(f"    {pc}: ({body},),  # {pc + 1:03d} {names}")
lines.append("}")
lines.append("# CM-64 tones whose tone data duplicates an 8850 tone or an earlier CM-64 slot.")
lines.append("_CM_DUP = frozenset({")
for k in cm_drop:
    lines.append(f"    {k},  # {name(k)}")
lines.append("})")
lines.append("# --- end generated ---")
block = "\n".join(lines)

path = os.path.join(REPO, "tables_8850.py")
src = open(path).read()
pat = re.compile(r"# --- generated by tools/gen_unique_tones.py.*?# --- end generated ---", re.S)
if pat.search(src):
    src = pat.sub(lambda _m: block, src)
else:
    src = src.replace("\n# CM-64 extras:", "\n" + block + "\n\n# CM-64 extras:", 1)
open(path, "w").write(src)
print(f"older maps: {sum(len(v) for v in old.values())} tones on {len(old)} programs; "
      f"CM-64 duplicates dropped: {len(cm_drop)} of {sum(len(v) for v in T._CM.values())}")
